### ISSUE TITLE
toString() method in BratRelation produces a wrong order of attributes

### ISSUE THREAD

**Issue by krischris** [yfpeng/pengyifan-brat#1]
Is:
"R1 likes Arg2:T1 Arg1:T2"

Should be:
"R1 likes Arg1:T2 Arg2:T1"

The root of the problem: 

```
public String toString() 
{
        StringBuilder sb = new StringBuilder(super.toString());
        Iterator var2 = this.getArguments().keySet().iterator();

        while(var2.hasNext()) {
            String role = (String)var2.next();
            sb.append(' ').append(role).append(':').append(this.getArgId(role));
        }

        return sb.toString();
    }
```

And, more specifically:  

```
Iterator var2 = this.getArguments().keySet().iterator();
```

The set doesn't preserve any ordering of the key elements. 
It's surprising that BratRelation class uses a HashMap internally where a simple
String[] arguments = new String[]{"Arg1", "Arg2"};
String [] values = new String[2]; 
and method setArgument(int, String)
would be sufficient. 
Is there any known implementation of Brat that uses more than two arguments in a relation? 

I'm using your Java Brat Library together with the standard "brat rapid annotation tool"
( http://brat.nlplab.org/index.html ). 

> The ordering of the arguments is crucial, because the "brat rapid annotation tool" 
> is unable to edit/ remove a relation annotation whose "Arg1" / "Arg2" are in reversed order.

**Comment by yfpeng** [comment]
Hi, theoretically brat doesn't require arguments in order. Suppose one
argument is "Experiencer" the other is "Theme", it is hard to tell which
one should go first. I chose Map instead of List because it should be
faster for search.

I also notice that Brat visualization requires "Arg1" goes before "Arg2",
and I remember only "Arg1" and "Arg2" are allowed in this tool so far.  If
so,  I would suggest you to generate the .ann file yourself.

Best,
Yifan

**Comment by krischris** [comment]
So we agree that Brat doesn't specify more than two arguments in a relation? 
That's great, so we could roll out an implementation based on a String array
and two dedicated getters, getFromId and getToId, which would be much more readable and about 10 times faster, by my measurements. 

The following code wouldn't break the backward compatibility and would be 5 to 10 times faster.
And would cooperate with brat annotation tool out of the box. 
Sample code:

```
  public String getArgId(String key){
        if(argKeys[0].equals(key)) return argValues[0];
        if(argKeys[1].equals(key)) return argValues[1];
        return null;
    }

```

**Comment by yfpeng** [comment]
Form their specification, yes

Relation annotations

Binary relations have a unique ID and are defined by their type (e.g. Origin,
Part-of) and their arguments.
  R1Origin Arg1:T3 Arg2:T4  The format is similar to that applied for
events, with the exception that the annotation does not identify a specific
piece of text expressing the relation ("trigger"): the ID is separated by a
TAB character, and the relation type and arguments by SPACE.

Relation arguments are commonly identified simply as Arg1 and Arg2, but the
system can be configured to use any labels (e.g. Anaphor and Antecedent) in
the standoff representation.

Yifan

**Comment by yfpeng** [comment]
I changed the code in BratRelation and BratEvent. In the toString method, I sort the argument before print them out. So "Arg1" will always go before "Arg2". I hope this can fix the problem of Brat visualization tool and keep the interface same.

**Comment by krischris** [comment]
Thanks! I think that something like that solves the main issue.
